site_name: PiT4Extia
site_url: https://PiToGit.github.io/Docs_tech
site_author: Patrick 'PiT' Lefranc
site_description: >-
  Comment expliquer le métier de la production Informatique à des personne non initié ou qui veulent en savoir plus.

# Repository
repo_name: PiToGit/Docs_tech
repo_url: https://github.com/PiToGit/Docs_tech

# Copyright
copyright: Copyright &copy; 2025 PiT

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
    #- announce.dismiss
    #- content.action.edit
    #- content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Nova Square
    code: Nova Square Mono
  favicon: Logo_Extia.png
  icon:
  theme:
    icon:
      admonition:
        note: octicons/clipboard
        abstract: fontawesome/regular/clipboard-list
        info: fontawesome/solid/circle-info
        tip: octicons/squirrel-16
        success: octicons/check-16
        question: fontawesome/solid/question
        warning: fontawesome/solid/triangle-exclamation
        failure: octicons/x-circle-16
        danger: fontawesome/solid/skull-crossbones
        bug: octicons/bug-16
        example: octicons/beaker-16
        quote: octicons/quote-16
      annotation: material/arrow-right-circle

  logo: Logo_Extia.png

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - drawio:
      darkmode: true

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/extia/posts/?feedView=all
    - icon: fontawesome/brands/discord
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/extia_conseil/?hl=fr


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

not_in_nav: 

# Page tree
nav:
  - Home: index.md
  - EMS: ems.md

