site_name: PiT4Extia
site_url: https://PiToGit.github.io/Docs_tech
site_author: Patrick 'PiT' Lefranc
site_description: >-
  Comment expliquer le métier de la production Informatique à des personne non initié ou qui veulent en savoir plus.

# Repository
repo_name: PiToGit/Docs_tech
repo_url: https://github.com/PiToGit/Docs_tech

# Copyright
copyright: Copyright &copy; 2025 PiT

# Configuration
theme:
  name: mkdocs